/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_physicsworld_free: (a: number, b: number) => void;
export const physicsworld_add_beam: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => void;
export const physicsworld_add_node: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => void;
export const physicsworld_add_triangle: (a: number, b: number, c: number, d: number) => void;
export const physicsworld_add_vehicle: (a: number, b: number, c: number, d: number) => number;
export const physicsworld_apply_force: (a: number, b: number, c: number, d: number, e: number) => void;
export const physicsworld_clear_tcm_faults: (a: number) => void;
export const physicsworld_configure_runtime: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number, p: number, q: number, r: number, s: number, t: number, u: number, v: number, w: number, x: number, y: number, z: number, a1: number, b1: number, c1: number, d1: number, e1: number, f1: number, g1: number, h1: number, i1: number, j1: number, k1: number, l1: number, m1: number, n1: number, o1: number, p1: number, q1: number, r1: number) => void;
export const physicsworld_get_beam_count: (a: number) => number;
export const physicsworld_get_node_count: (a: number) => number;
export const physicsworld_get_positions_flat: (a: number) => [number, number];
export const physicsworld_get_telemetry_flat: (a: number) => [number, number];
export const physicsworld_get_velocities_flat: (a: number) => [number, number];
export const physicsworld_new: () => number;
export const physicsworld_set_adas_target: (a: number, b: number, c: number) => void;
export const physicsworld_set_automatic_shift_schedule: (a: number, b: number, c: number) => void;
export const physicsworld_set_controls: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => void;
export const physicsworld_set_node_collision: (a: number, b: number, c: number) => void;
export const physicsworld_set_tcm_fault: (a: number, b: number, c: number) => void;
export const physicsworld_set_tcm_fault_intermittent: (a: number, b: number, c: number) => void;
export const physicsworld_set_tcm_fault_seed: (a: number, b: bigint) => void;
export const physicsworld_set_terrain_profile: (a: number, b: number) => void;
export const physicsworld_set_transmission_mode: (a: number, b: number) => void;
export const physicsworld_step: (a: number, b: number) => void;
export const physicsworld_get_time: (a: number) => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
