use serde::{Deserialize, Serialize};

/// Thermal model for engine coolant, oil, and transmission temperatures.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EngineThermal {
    pub coolant_temp: f64,
    pub oil_temp: f64,
    pub transmission_temp: f64,
    pub ambient_temp: f64,
    pub coolant_capacity: f64,
    pub oil_capacity: f64,
    pub coolant_specific_heat: f64,
    pub oil_specific_heat: f64,
    pub combustion_heat_rate: f64,
    pub friction_heat_rate: f64,
    pub exhaust_heat_fraction: f64,
}

impl Default for EngineThermal {
    fn default() -> Self {
        Self {
            coolant_temp: 20.0,
            oil_temp: 20.0,
            transmission_temp: 20.0,
            ambient_temp: 25.0,
            coolant_capacity: 6.0,
            oil_capacity: 4.0,
            coolant_specific_heat: 4186.0,
            oil_specific_heat: 2000.0,
            combustion_heat_rate: 5000.0,
            friction_heat_rate: 800.0,
            exhaust_heat_fraction: 0.35,
        }
    }
}

/// Cooling system: radiator, fan, thermostat, airflow.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CoolingSystem {
    pub radiator_capacity: f64,
    pub fan_activation_temp: f64,
    pub fan_additional_cooling: f64,
    pub thermostat_open_temp: f64,
    pub thermostat_range: f64,
    pub coolant_flow_rate: f64,
    pub damage_factor: f64,
}

impl Default for CoolingSystem {
    fn default() -> Self {
        Self {
            radiator_capacity: 8000.0,
            fan_activation_temp: 95.0,
            fan_additional_cooling: 3000.0,
            thermostat_open_temp: 82.0,
            thermostat_range: 13.0,
            coolant_flow_rate: 1.0,
            damage_factor: 1.0,
        }
    }
}

impl CoolingSystem {
    /// Thermostat valve position 0-1 based on coolant temperature.
    pub fn thermostat_valve(&self, coolant_temp: f64) -> f64 {
        if coolant_temp <= self.thermostat_open_temp {
            0.0
        } else if coolant_temp >= self.thermostat_open_temp + self.thermostat_range {
            1.0
        } else {
            (coolant_temp - self.thermostat_open_temp) / self.thermostat_range
        }
    }

    /// Whether fan is active.
    pub fn fan_active(&self, coolant_temp: f64) -> bool {
        coolant_temp >= self.fan_activation_temp
    }

    /// Total cooling rate (W/°C) from radiator + fan, scaled by airflow and damage.
    pub fn cooling_rate(&self, coolant_temp: f64, vehicle_speed: f64) -> f64 {
        let valve = self.thermostat_valve(coolant_temp).clamp(0.0, 1.0);
        let speed = if vehicle_speed.is_finite() {
            vehicle_speed.abs()
        } else {
            0.0
        };
        let airflow = 0.3 + 0.7 * (speed / 30.0).clamp(0.0, 1.0);
        let damage = self.damage_factor.max(0.0);
        let mut rate = self.radiator_capacity.max(0.0) * valve * airflow * damage;
        if self.fan_active(coolant_temp) {
            rate += self.fan_additional_cooling.max(0.0) * damage;
        }
        rate * self.coolant_flow_rate.max(0.0)
    }
}

/// Lubrication system: oil pressure, viscosity, pump, pickup, level.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LubricationSystem {
    pub oil_pressure: f64,
    pub nominal_pressure: f64,
    pub pump_pressure: f64,
    pub pickup_position: f64,
    pub oil_level: f64,
    pub is_leaking: bool,
    pub leak_rate: f64,
}

impl Default for LubricationSystem {
    fn default() -> Self {
        Self {
            oil_pressure: 300.0,
            nominal_pressure: 300.0,
            pump_pressure: 400.0,
            pickup_position: 0.0,
            oil_level: 1.0,
            is_leaking: false,
            leak_rate: 0.0,
        }
    }
}

impl LubricationSystem {
    /// Oil viscosity (simplified): high when cold, low when hot. Normalized 0-1.
    pub fn viscosity(&self, oil_temp: f64) -> f64 {
        // Viscosity peaks when cold (~0.9 at 20°C), drops to ~0.3 at 150°C
        (1.0 - (oil_temp - 20.0) / 200.0).clamp(0.15, 1.0)
    }

    pub fn is_starved(&self) -> bool {
        self.oil_pressure < 50.0
    }

    /// Update lubrication state based on G-forces and dt.
    pub fn update(&mut self, accel_longitudinal_g: f64, dt: f64) {
        self.update_with_pump_factor(accel_longitudinal_g, dt, 1.0);
    }

    /// Update lubrication state with an engine-speed-dependent oil-pump
    /// output. A stopped engine has no pump pressure; the gallery pressure
    /// decays instead of being regenerated by a static pump model.
    pub fn update_with_engine_rpm(&mut self, accel_longitudinal_g: f64, dt: f64, rpm: f64) {
        let pump_factor = if rpm.is_finite() && rpm > 0.0 {
            (rpm / 800.0).clamp(0.0, 1.0)
        } else {
            0.0
        };
        self.update_with_pump_factor(accel_longitudinal_g, dt, pump_factor);
    }

    fn update_with_pump_factor(&mut self, accel_longitudinal_g: f64, dt: f64, pump_factor: f64) {
        // Sump movement: positive accel pushes oil back (pickup exposure)
        let safe_accel = if accel_longitudinal_g.is_finite() {
            accel_longitudinal_g
        } else {
            0.0
        };
        self.pickup_position = (safe_accel * 0.3).clamp(-1.0, 1.0).max(0.0);

        // Leak
        if self.is_leaking {
            self.oil_level = (self.oil_level - self.leak_rate.max(0.0) * dt.max(0.0)).max(0.0);
        }

        // Pressure from pump, modified by level and pickup exposure
        let level_factor = self.oil_level.clamp(0.0, 1.0);
        let pickup_factor = 1.0 - self.pickup_position * 0.7;
        let target_pressure = self.pump_pressure.max(0.0)
            * pump_factor.clamp(0.0, 1.0)
            * level_factor
            * pickup_factor.max(0.0);
        let safe_dt = dt.max(0.0);
        if pump_factor > 0.0 {
            self.oil_pressure = target_pressure;
        } else {
            let pressure_decay = (1.0 - 8.0 * safe_dt).max(0.0);
            self.oil_pressure = (self.oil_pressure.max(0.0) * pressure_decay).max(0.0);
        }
    }
}
