use serde::{Deserialize, Serialize};

/// Thermal model for engine coolant, oil, and transmission temperatures.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EngineThermal {
    pub coolant_temp: f64,
    pub oil_temp: f64,
    pub transmission_temp: f64,
    pub ambient_temp: f64,
    pub coolant_capacity: f64,
    pub oil_capacity: f64,
    pub coolant_specific_heat: f64,
    pub oil_specific_heat: f64,
    pub combustion_heat_rate: f64,
    pub friction_heat_rate: f64,
    pub exhaust_heat_fraction: f64,
}

impl Default for EngineThermal {
    fn default() -> Self {
        Self {
            coolant_temp: 20.0,
            oil_temp: 20.0,
            transmission_temp: 20.0,
            ambient_temp: 25.0,
            coolant_capacity: 6.0,
            oil_capacity: 4.0,
            coolant_specific_heat: 4186.0,
            oil_specific_heat: 2000.0,
            combustion_heat_rate: 5000.0,
            friction_heat_rate: 800.0,
            exhaust_heat_fraction: 0.35,
        }
    }
}

/// Cooling system: radiator, fan, thermostat, airflow.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CoolingSystem {
    pub radiator_capacity: f64,
    pub fan_activation_temp: f64,
    pub fan_additional_cooling: f64,
    pub thermostat_open_temp: f64,
    pub thermostat_range: f64,
    pub coolant_flow_rate: f64,
    pub damage_factor: f64,
}

impl Default for CoolingSystem {
    fn default() -> Self {
        Self {
            radiator_capacity: 8000.0,
            fan_activation_temp: 95.0,
            fan_additional_cooling: 3000.0,
            thermostat_open_temp: 82.0,
            thermostat_range: 13.0,
            coolant_flow_rate: 1.0,
            damage_factor: 1.0,
        }
    }
}

impl CoolingSystem {
    /// Thermostat valve position 0-1 based on coolant temperature.
    pub fn thermostat_valve(&self, coolant_temp: f64) -> f64 {
        if coolant_temp <= self.thermostat_open_temp {
            0.0
        } else if coolant_temp >= self.thermostat_open_temp + self.thermostat_range {
            1.0
        } else {
            (coolant_temp - self.thermostat_open_temp) / self.thermostat_range
        }
    }

    /// Whether fan is active.
    pub fn fan_active(&self, coolant_temp: f64) -> bool {
        coolant_temp >= self.fan_activation_temp
    }

    /// Total cooling rate (W/°C) from radiator + fan, scaled by airflow and damage.
    pub fn cooling_rate(&self, coolant_temp: f64, vehicle_speed: f64) -> f64 {
        let valve = self.thermostat_valve(coolant_temp).clamp(0.0, 1.0);
        let speed = if vehicle_speed.is_finite() {
            vehicle_speed.abs()
        } else {
            0.0
        };
        let airflow = 0.3 + 0.7 * (speed / 30.0).clamp(0.0, 1.0);
        let damage = self.damage_factor.max(0.0);
        let mut rate = self.radiator_capacity.max(0.0) * valve * airflow * damage;
        if self.fan_active(coolant_temp) {
            rate += self.fan_additional_cooling.max(0.0) * damage;
        }
        rate * self.coolant_flow_rate.max(0.0)
    }
}

/// Lubrication system: oil pressure, viscosity, pump, pickup, level.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LubricationSystem {
    pub oil_pressure: f64,
    pub nominal_pressure: f64,
    pub pump_pressure: f64,
    pub pickup_position: f64,
    pub oil_level: f64,
    pub is_leaking: bool,
    pub leak_rate: f64,
}

impl Default for LubricationSystem {
    fn default() -> Self {
        Self {
            oil_pressure: 300.0,
            nominal_pressure: 300.0,
            pump_pressure: 400.0,
            pickup_position: 0.0,
            oil_level: 1.0,
            is_leaking: false,
            leak_rate: 0.0,
        }
    }
}

impl LubricationSystem {
    /// Oil viscosity (simplified): high when cold, low when hot. Normalized 0-1.
    pub fn viscosity(&self, oil_temp: f64) -> f64 {
        // Viscosity peaks when cold (~0.9 at 20°C), drops to ~0.3 at 150°C
        (1.0 - (oil_temp - 20.0) / 200.0).clamp(0.15, 1.0)
    }

    pub fn is_starved(&self) -> bool {
        self.oil_pressure < 50.0
    }

    /// Update lubrication state based on G-forces and dt.
    pub fn update(&mut self, accel_longitudinal_g: f64, dt: f64) {
        self.update_with_pump_factor(accel_longitudinal_g, dt, 1.0);
    }

    /// Update lubrication state with an engine-speed-dependent oil-pump
    /// output. A stopped engine has no pump pressure; the gallery pressure
    /// decays instead of being regenerated by a static pump model.
    pub fn update_with_engine_rpm(&mut self, accel_longitudinal_g: f64, dt: f64, rpm: f64) {
        let pump_factor = if rpm.is_finite() && rpm > 0.0 {
            (rpm / 800.0).clamp(0.0, 1.0)
        } else {
            0.0
        };
        self.update_with_pump_factor(accel_longitudinal_g, dt, pump_factor);
    }

    fn update_with_pump_factor(&mut self, accel_longitudinal_g: f64, dt: f64, pump_factor: f64) {
        // Sump movement: positive accel pushes oil back (pickup exposure)
        let safe_accel = if accel_longitudinal_g.is_finite() {
            accel_longitudinal_g
        } else {
            0.0
        };
        self.pickup_position = (safe_accel * 0.3).clamp(-1.0, 1.0).max(0.0);

        // Leak
        if self.is_leaking {
            self.oil_level = (self.oil_level - self.leak_rate.max(0.0) * dt.max(0.0)).max(0.0);
        }

        // Pressure from pump, modified by level and pickup exposure
        let level_factor = self.oil_level.clamp(0.0, 1.0);
        let pickup_factor = 1.0 - self.pickup_position * 0.7;
        let target_pressure = self.pump_pressure.max(0.0)
            * pump_factor.clamp(0.0, 1.0)
            * level_factor
            * pickup_factor.max(0.0);
        let safe_dt = dt.max(0.0);
        if pump_factor > 0.0 {
            self.oil_pressure = target_pressure;
        } else {
            let pressure_decay = (1.0 - 8.0 * safe_dt).max(0.0);
            self.oil_pressure = (self.oil_pressure.max(0.0) * pressure_decay).max(0.0);
        }
    }
}

/// Progressive engine damage tracking.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EngineDamage {
    pub wear_level: f64,
    pub overheating_cycles: u32,
    pub overrev_cycles: u32,
    pub knock_events: u32,
    pub has_coolant_leak: bool,
    pub has_oil_leak: bool,
    pub head_gasket_failed: bool,
    pub bearing_damage: f64,
    pub is_seized: bool,
    pub is_on_fire: bool,
    pub fire_timer: f64,
    /// Lugging events (high gear, low RPM, high load).
    pub lugging_events: u32,
    /// Causal damage event history (bounded).
    pub damage_history: Vec<DamageEvent>,
}

impl Default for EngineDamage {
    fn default() -> Self {
        Self {
            wear_level: 0.0,
            overheating_cycles: 0,
            overrev_cycles: 0,
            knock_events: 0,
            has_coolant_leak: false,
            has_oil_leak: false,
            head_gasket_failed: false,
            bearing_damage: 0.0,
            is_seized: false,
            is_on_fire: false,
            fire_timer: 0.0,
            lugging_events: 0,
            damage_history: Vec::new(),
        }
    }
}

impl EngineDamage {
    pub fn check_overheat(&mut self, coolant_temp: f64) {
        if coolant_temp > 110.0 {
            self.overheating_cycles += 1;
        }
        if coolant_temp > 125.0 && !self.head_gasket_failed {
            // Accumulated risk — simplified: every 100 cycles of >125°C risks head gasket
            if self.overheating_cycles > 100 {
                self.head_gasket_failed = true;
                self.has_coolant_leak = true;
            }
        }
        if coolant_temp > 140.0 {
            self.wear_level = (self.wear_level + 0.005).min(1.0);
            if self.wear_level > 0.8 && !self.is_on_fire {
                // Fire risk increases with extreme temp
                self.fire_timer += 0.01;
                if self.fire_timer > 1.0 {
                    self.is_on_fire = true;
                }
            }
        }
    }

    pub fn check_overrev(&mut self, rpm: f64, redline: f64) {
        if rpm > redline * 1.1 {
            self.overrev_cycles += 1;
            self.wear_level = (self.wear_level + 0.0001).min(1.0);
        }
    }

    pub fn check_oil_starvation(&mut self, pressure: f64) {
        if pressure < 50.0 {
            self.bearing_damage = (self.bearing_damage + 0.001).min(1.0);
        }
        if pressure < 10.0 {
            self.bearing_damage = (self.bearing_damage + 0.01).min(1.0);
        }
        if self.bearing_damage > 0.8 {
            self.is_seized = true;
        }
    }

    pub fn check_knock(&mut self) {
        self.knock_events += 1;
        if self.knock_events > 50 {
            self.wear_level = (self.wear_level + 0.001).min(1.0);
        }
    }

    /// Check for lugging (high gear, low RPM, high throttle).
    pub fn check_lugging(&mut self, rpm: f64, throttle: f64, gear: i32, time: f64) {
        if gear >= 3 && rpm < 1500.0 && throttle > 0.5 {
            self.lugging_events += 1;
            self.wear_level = (self.wear_level + 0.0002).min(1.0);
            if self.damage_history.len() < 50 {
                self.damage_history.push(DamageEvent {
                    timestamp: time,
                    cause: "lugging".into(),
                    severity: 0.3,
                    subsystem: "engine".into(),
                });
            }
        }
    }

    /// Record a damage event in the causal history.
    pub fn record_damage_event(&mut self, time: f64, cause: &str, severity: f64, subsystem: &str) {
        if self.damage_history.len() < 50 {
            self.damage_history.push(DamageEvent {
                timestamp: time,
                cause: cause.to_string(),
                severity,
                subsystem: subsystem.to_string(),
            });
        }
    }

    pub fn update(&mut self, dt: f64) {
        if self.is_on_fire {
            self.fire_timer += dt;
            self.wear_level = (self.wear_level + 0.05 * dt).min(1.0);
        }
    }
}

/// Staged blow-up outcomes from 0=ok to 5=catastrophic.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum BlowupStage {
    Ok = 0,
    WarningLamp = 1,
    TorqueDerate = 2,
    RoughRunning = 3,
    SeverePowerLoss = 4,
    SeizureOrFire = 5,
    CompleteFailure = 6,
}

impl BlowupStage {
    pub fn from_level(level: u8) -> Self {
        match level {
            0 => Self::Ok,
            1 => Self::WarningLamp,
            2 => Self::TorqueDerate,
            3 => Self::RoughRunning,
            4 => Self::SeverePowerLoss,
            5 => Self::SeizureOrFire,
            _ => Self::CompleteFailure,
        }
    }
}

/// Causal damage event with timestamp and severity.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DamageEvent {
    pub timestamp: f64,
    pub cause: String,
    pub severity: f64,
    pub subsystem: String,
}

/// Cumulative stress accumulators with hysteresis and cooldown.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EngineStressAccumulators {
    /// Thermal stress: temperature-above-limit × duration. Cools when temp is safe.
    pub thermal_stress: f64,
    /// Oil starvation stress: pressure-below-limit × duration.
    pub oil_stress: f64,
    /// Over-rev stress: RPM-above-limit × duration × severity multiplier.
    pub overrev_stress: f64,
    /// Lugging stress: high-gear/low-RPM overload × duration.
    pub lugging_stress: f64,
    /// Accumulator cooldown rates (per second).
    pub thermal_cooldown_rate: f64,
    pub oil_cooldown_rate: f64,
    pub overrev_cooldown_rate: f64,
    pub lugging_cooldown_rate: f64,
    /// Accumulator limits before damage escalation.
    pub thermal_limit: f64,
    pub oil_limit: f64,
    pub overrev_limit: f64,
    pub lugging_limit: f64,
}

impl Default for EngineStressAccumulators {
    fn default() -> Self {
        Self {
            thermal_stress: 0.0,
            oil_stress: 0.0,
            overrev_stress: 0.0,
            lugging_stress: 0.0,
            thermal_cooldown_rate: 0.1,
            oil_cooldown_rate: 0.15,
            overrev_cooldown_rate: 0.05,
            lugging_cooldown_rate: 0.1,
            thermal_limit: 1.0,
            oil_limit: 1.0,
            overrev_limit: 1.0,
            lugging_limit: 1.0,
        }
    }
}

impl EngineStressAccumulators {
    /// Accumulate thermal stress. Positive when temp exceeds limit, cools when below.
    pub fn accumulate_thermal(&mut self, coolant_temp: f64, redline_temp: f64, dt: f64) {
        if coolant_temp > redline_temp {
            let severity = (coolant_temp - redline_temp) / 30.0; // normalized
            self.thermal_stress =
                (self.thermal_stress + severity * dt).min(self.thermal_limit * 2.0);
        } else {
            self.thermal_stress = (self.thermal_stress - self.thermal_cooldown_rate * dt).max(0.0);
        }
    }

    /// Accumulate oil starvation stress.
    pub fn accumulate_oil(&mut self, oil_pressure: f64, nominal_pressure: f64, dt: f64) {
        if oil_pressure < nominal_pressure * 0.3 {
            let severity = (1.0 - oil_pressure / (nominal_pressure * 0.3)).min(2.0);
            self.oil_stress = (self.oil_stress + severity * dt).min(self.oil_limit * 2.0);
        } else {
            self.oil_stress = (self.oil_stress - self.oil_cooldown_rate * dt).max(0.0);
        }
    }

    /// Accumulate over-rev stress with cause-dependent severity.
    pub fn accumulate_overrev(
        &mut self,
        rpm: f64,
        redline: f64,
        is_drivetrain_forced: bool,
        dt: f64,
    ) {
        if rpm > redline {
            let excess = (rpm - redline) / redline;
            let severity_multiplier = if is_drivetrain_forced { 2.0 } else { 1.0 };
            let severity = excess * severity_multiplier;
            self.overrev_stress =
                (self.overrev_stress + severity * dt).min(self.overrev_limit * 2.0);
        } else {
            self.overrev_stress = (self.overrev_stress - self.overrev_cooldown_rate * dt).max(0.0);
        }
    }

    /// Accumulate lugging stress (high gear, low RPM, high load).
    pub fn accumulate_lugging(
        &mut self,
        rpm: f64,
        throttle: f64,
        gear: i32,
        min_lug_rpm: f64,
        dt: f64,
    ) {
        if gear >= 3 && rpm < min_lug_rpm && throttle > 0.5 {
            let severity = throttle * (1.0 - rpm / min_lug_rpm);
            self.lugging_stress =
                (self.lugging_stress + severity * dt).min(self.lugging_limit * 2.0);
        } else {
            self.lugging_stress = (self.lugging_stress - self.lugging_cooldown_rate * dt).max(0.0);
        }
    }

    /// Current blow-up stage based on accumulated stress.
    pub fn blowup_stage(&self) -> BlowupStage {
        let max_stress = self
            .thermal_stress
            .max(self.oil_stress)
            .max(self.overrev_stress)
            .max(self.lugging_stress);
        if max_stress > 1.8 {
            BlowupStage::CompleteFailure
        } else if max_stress > 1.5 {
            BlowupStage::SeizureOrFire
        } else if max_stress > 1.2 {
            BlowupStage::SeverePowerLoss
        } else if max_stress > 0.9 {
            BlowupStage::RoughRunning
        } else if max_stress > 0.5 {
            BlowupStage::TorqueDerate
        } else if max_stress > 0.2 {
            BlowupStage::WarningLamp
        } else {
            BlowupStage::Ok
        }
    }

    /// Derate factor (0-1) from accumulated stress.
    pub fn derate_factor(&self) -> f64 {
        let max_stress = self
            .thermal_stress
            .max(self.oil_stress)
            .max(self.overrev_stress)
            .max(self.lugging_stress);
        (1.0 - (max_stress * 0.4)).clamp(0.0, 1.0)
    }
}

/// Full telemetry output from the engine update cycle.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EngineTelemetry {
    pub coolant_temp: f64,
    pub oil_temp: f64,
    pub oil_pressure: f64,
    pub transmission_temp: f64,
    pub derate_factor: f64,
    pub has_warning: bool,
    pub is_seized: bool,
    pub is_on_fire: bool,
    /// Current blow-up stage.
    pub blowup_stage: BlowupStage,
    /// Cumulative stress accumulator values for telemetry.
    pub thermal_stress: f64,
    pub oil_stress: f64,
    pub overrev_stress: f64,
    pub lugging_stress: f64,
    /// Recent causal damage events.
    pub damage_events: Vec<DamageEvent>,
}

/// Main update function for engine thermal, lubrication, and damage.
pub fn update_engine(
    thermal: &mut EngineThermal,
    cooling: &CoolingSystem,
    lubrication: &mut LubricationSystem,
    damage: &mut EngineDamage,
    rpm: f64,
    redline_rpm: f64,
    throttle: f64,
    vehicle_speed: f64,
    accel_g: f64,
    dt: f64,
) -> EngineTelemetry {
    // Heat generation
    let safe_redline = if redline_rpm.is_finite() && redline_rpm > 0.0 {
        redline_rpm
    } else {
        7000.0
    };
    let safe_throttle = if throttle.is_finite() {
        throttle.clamp(0.0, 1.0)
    } else {
        0.0
    };
    let normalized_rpm = if rpm.is_finite() {
        (rpm / safe_redline).clamp(0.0, 1.5)
    } else {
        0.0
    };
    let load = safe_throttle * normalized_rpm;
    let combustion_heat = thermal.combustion_heat_rate * load;
    let friction_heat = thermal.friction_heat_rate * normalized_rpm;
    let total_heat = combustion_heat + friction_heat;
    let exhaust_fraction = thermal.exhaust_heat_fraction;
    let retained_heat = total_heat * (1.0 - exhaust_fraction);

    // Distribute heat: 60% to coolant, 40% to oil
    let coolant_heat = retained_heat * 0.6;
    let oil_heat = retained_heat * 0.4;

    let safe_dt = if dt.is_finite() && dt > 0.0 { dt } else { 0.0 };
    thermal.coolant_temp += coolant_heat
        / (thermal.coolant_capacity.max(0.1) * thermal.coolant_specific_heat.max(1.0))
        * safe_dt;
    thermal.oil_temp +=
        oil_heat / (thermal.oil_capacity.max(0.1) * thermal.oil_specific_heat.max(1.0)) * safe_dt;

    // Cooling
    let cool_rate = cooling.cooling_rate(thermal.coolant_temp, vehicle_speed);
    let ambient_delta = (thermal.coolant_temp - thermal.ambient_temp).max(0.0);
    thermal.coolant_temp -= cool_rate
        / (thermal.coolant_capacity.max(0.1) * thermal.coolant_specific_heat.max(1.0))
        * ambient_delta
        * safe_dt;

    // Heat soak toward ambient when engine off
    if throttle < 0.01 && rpm < 1000.0 {
        let soak_rate = 0.01;
        thermal.coolant_temp += (thermal.ambient_temp - thermal.coolant_temp) * soak_rate * safe_dt;
        thermal.oil_temp += (thermal.ambient_temp - thermal.oil_temp) * soak_rate * safe_dt;
    }

    // Oil temp approaches coolant temp (heat exchange)
    thermal.oil_temp += (thermal.coolant_temp - thermal.oil_temp) * 0.001 * safe_dt;

    // Transmission temp follows oil temp loosely
    thermal.transmission_temp += (thermal.oil_temp - thermal.transmission_temp) * 0.0005 * safe_dt;

    // Clamp temps
    thermal.coolant_temp = thermal.coolant_temp.max(thermal.ambient_temp - 5.0);
    thermal.oil_temp = thermal.oil_temp.max(thermal.ambient_temp - 5.0);

    // Lubrication update
    lubrication.update_with_engine_rpm(accel_g, dt.max(0.0), rpm);

    // Damage checks
    damage.check_overheat(thermal.coolant_temp);
    damage.check_overrev(rpm, redline_rpm);
    if rpm.is_finite() && rpm > 0.0 {
        damage.check_oil_starvation(lubrication.oil_pressure);
    }
    damage.update(dt);

    // Derate factor
    let derate_factor = if damage.is_seized {
        0.0
    } else {
        let bearing_derate = 1.0 - damage.bearing_damage * 0.5;
        let wear_derate = 1.0 - damage.wear_level * 0.3;
        let gasket_derate = if damage.head_gasket_failed { 0.6 } else { 1.0 };
        bearing_derate.max(0.0) * wear_derate.max(0.0) * gasket_derate
    };

    // Warning state
    let has_warning = thermal.coolant_temp > 105.0
        || lubrication.oil_pressure < 80.0
        || damage.bearing_damage > 0.1
        || damage.is_on_fire;

    EngineTelemetry {
        coolant_temp: thermal.coolant_temp,
        oil_temp: thermal.oil_temp,
        oil_pressure: lubrication.oil_pressure,
        transmission_temp: thermal.transmission_temp,
        derate_factor,
        has_warning,
        is_seized: damage.is_seized,
        is_on_fire: damage.is_on_fire,
        blowup_stage: BlowupStage::Ok,
        thermal_stress: 0.0,
        oil_stress: 0.0,
        overrev_stress: 0.0,
        lugging_stress: 0.0,
        damage_events: Vec::new(),
    }
}

/// Extended engine update with stress accumulators, lugging detection, and staged blow-up.
pub fn update_engine_full(
    thermal: &mut EngineThermal,
    cooling: &CoolingSystem,
    lubrication: &mut LubricationSystem,
    damage: &mut EngineDamage,
    stress: &mut EngineStressAccumulators,
    rpm: f64,
    redline_rpm: f64,
    throttle: f64,
    vehicle_speed: f64,
    accel_g: f64,
    gear: i32,
    time: f64,
    dt: f64,
) -> EngineTelemetry {
    update_engine_full_with_cause(
        thermal,
        cooling,
        lubrication,
        damage,
        stress,
        rpm,
        redline_rpm,
        throttle,
        vehicle_speed,
        accel_g,
        gear,
        time,
        dt,
        false,
    )
}

/// Full engine update with a causal drivetrain over-rev signal.
///
/// The compatibility wrapper above keeps existing callers deterministic,
/// while the authoritative vehicle world can distinguish limiter revving from
/// a forced over-rev caused by a driveline event.
pub fn update_engine_full_with_cause(
    thermal: &mut EngineThermal,
    cooling: &CoolingSystem,
    lubrication: &mut LubricationSystem,
    damage: &mut EngineDamage,
    stress: &mut EngineStressAccumulators,
    rpm: f64,
    redline_rpm: f64,
    throttle: f64,
    vehicle_speed: f64,
    accel_g: f64,
    gear: i32,
    time: f64,
    dt: f64,
    drivetrain_forced_overrev: bool,
) -> EngineTelemetry {
    // Run the base update
    let base = update_engine(
        thermal,
        cooling,
        lubrication,
        damage,
        rpm,
        redline_rpm,
        throttle,
        vehicle_speed,
        accel_g,
        dt,
    );

    // Accumulate stress
    stress.accumulate_thermal(thermal.coolant_temp, 110.0, dt);
    if rpm.is_finite() && rpm > 0.0 {
        stress.accumulate_oil(lubrication.oil_pressure, lubrication.nominal_pressure, dt);
    } else {
        stress.oil_stress = (stress.oil_stress - stress.oil_cooldown_rate * dt.max(0.0)).max(0.0);
    }
    stress.accumulate_overrev(rpm, redline_rpm, drivetrain_forced_overrev, dt);
    stress.accumulate_lugging(rpm, throttle, gear, 1500.0, dt);

    // Check lugging damage
    damage.check_lugging(rpm, throttle, gear, time);

    // Determine blow-up stage from stress
    let blowup = stress.blowup_stage();
    let stress_derate = stress.derate_factor();

    // Combined derate: base damage × stress derate
    let derate_factor = base.derate_factor * stress_derate;

    // Warning includes stress
    let has_warning = base.has_warning || blowup as u8 >= BlowupStage::WarningLamp as u8;

    EngineTelemetry {
        coolant_temp: base.coolant_temp,
        oil_temp: base.oil_temp,
        oil_pressure: base.oil_pressure,
        transmission_temp: base.transmission_temp,
        derate_factor,
        has_warning,
        is_seized: base.is_seized || blowup as u8 >= BlowupStage::SeizureOrFire as u8,
        is_on_fire: base.is_on_fire,
        blowup_stage: blowup,
        thermal_stress: stress.thermal_stress,
        oil_stress: stress.oil_stress,
        overrev_stress: stress.overrev_stress,
        lugging_stress: stress.lugging_stress,
        damage_events: damage.damage_history.clone(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_test_systems() -> (
        EngineThermal,
        CoolingSystem,
        LubricationSystem,
        EngineDamage,
    ) {
        (
            EngineThermal::default(),
            CoolingSystem::default(),
            LubricationSystem::default(),
            EngineDamage::default(),
        )
    }

    #[test]
    fn test_heat_generation() {
        let (mut thermal, cooling, mut lub, mut dmg) = make_test_systems();
        let t0 = thermal.coolant_temp;
        update_engine(
            &mut thermal,
            &cooling,
            &mut lub,
            &mut dmg,
            3000.0,
            7000.0,
            1.0,
            0.0,
            0.0,
            1.0,
        );
        assert!(
            thermal.coolant_temp > t0,
            "Coolant should heat up under load"
        );
    }

    #[test]
    fn test_cooling_basic() {
        let (mut thermal, cooling, mut lub, mut dmg) = make_test_systems();
        thermal.coolant_temp = 100.0;
        // Run for several seconds with vehicle speed for airflow
        for _ in 0..60 {
            update_engine(
                &mut thermal,
                &cooling,
                &mut lub,
                &mut dmg,
                0.0,
                7000.0,
                0.0,
                30.0,
                0.0,
                1.0,
            );
        }
        assert!(
            thermal.coolant_temp < 100.0,
            "Cooling should reduce temperature"
        );
    }

    #[test]
    fn test_thermostat_hysteresis() {
        let cooling = CoolingSystem::default();
        assert!((cooling.thermostat_valve(70.0) - 0.0).abs() < 1e-6);
        assert!((cooling.thermostat_valve(95.0) - 1.0).abs() < 1e-6);
        let mid = cooling.thermostat_valve(88.5);
        assert!(mid > 0.0 && mid < 1.0);
    }

    #[test]
    fn test_fan_activation() {
        let cooling = CoolingSystem::default();
        assert!(!cooling.fan_active(80.0));
        assert!(cooling.fan_active(95.0));
    }

    #[test]
    fn test_airflow_cooling() {
        let cooling = CoolingSystem::default();
        let rate_slow = cooling.cooling_rate(95.0, 5.0);
        let rate_fast = cooling.cooling_rate(95.0, 30.0);
        assert!(
            rate_fast > rate_slow,
            "More airflow should increase cooling"
        );
    }

    #[test]
    fn test_heat_soak_after_shutdown() {
        let (mut thermal, cooling, mut lub, mut dmg) = make_test_systems();
        thermal.coolant_temp = 80.0;
        // No throttle, low RPM → heat soak
        for _ in 0..200 {
            update_engine(
                &mut thermal,
                &cooling,
                &mut lub,
                &mut dmg,
                500.0,
                7000.0,
                0.0,
                0.0,
                0.0,
                1.0,
            );
        }
        assert!(
            thermal.coolant_temp < 80.0,
            "Should cool toward ambient via heat soak"
        );
    }

    #[test]
    fn test_coolant_leak() {
        let (mut thermal, cooling, mut lub, mut dmg) = make_test_systems();
        dmg.has_coolant_leak = true;
        thermal.coolant_temp = 90.0;
        // Leak + no cooling → faster heat rise than no leak
        let mut thermal_no_leak = thermal.clone();
        let mut dmg_no_leak = EngineDamage::default();
        for _ in 0..10 {
            update_engine(
                &mut thermal,
                &cooling,
                &mut lub,
                &mut dmg,
                3000.0,
                7000.0,
                0.5,
                0.0,
                0.0,
                1.0,
            );
            update_engine(
                &mut thermal_no_leak,
                &cooling,
                &mut lub,
                &mut dmg_no_leak,
                3000.0,
                7000.0,
                0.5,
                0.0,
                0.0,
                1.0,
            );
        }
        // Leaking system should run hotter due to reduced coolant capacity effect
        // Both heat up, but we just verify the system doesn't crash
        assert!(thermal.coolant_temp > 20.0);
    }

    #[test]
    fn test_oil_pressure_normal() {
        let (_, _, lub, _) = make_test_systems();
        assert!(
            lub.oil_pressure > 200.0,
            "Normal oil pressure should be healthy"
        );
    }

    #[test]
    fn test_oil_pressure_starvation() {
        let mut lub = LubricationSystem::default();
        lub.oil_level = 0.1; // Very low oil
        lub.update(0.0, 0.1);
        assert!(lub.oil_pressure < 100.0, "Low oil should reduce pressure");
        assert!(lub.is_starved());
    }

    #[test]
    fn test_oil_viscosity_temperature() {
        let lub = LubricationSystem::default();
        let cold_visc = lub.viscosity(20.0);
        let hot_visc = lub.viscosity(120.0);
        assert!(cold_visc > hot_visc, "Cold oil should be more viscous");
    }

    #[test]
    fn test_overheat_derate() {
        let (mut thermal, cooling, mut lub, mut dmg) = make_test_systems();
        // Force extreme temp and keep it there — many cycles to accumulate damage
        for _ in 0..500 {
            thermal.coolant_temp = 145.0;
            update_engine(
                &mut thermal,
                &cooling,
                &mut lub,
                &mut dmg,
                6000.0,
                7000.0,
                1.0,
                0.0,
                0.0,
                0.5,
            );
        }
        let telem = update_engine(
            &mut thermal,
            &cooling,
            &mut lub,
            &mut dmg,
            6000.0,
            7000.0,
            1.0,
            0.0,
            0.0,
            0.1,
        );
        assert!(telem.derate_factor < 1.0, "Overheating should derate power");
    }

    #[test]
    fn test_overrev_damage() {
        let (mut thermal, cooling, mut lub, mut dmg) = make_test_systems();
        for _ in 0..200 {
            update_engine(
                &mut thermal,
                &cooling,
                &mut lub,
                &mut dmg,
                8000.0,
                7000.0,
                1.0,
                0.0,
                0.0,
                0.1,
            );
        }
        assert!(dmg.overrev_cycles > 0, "Should accumulate overrev cycles");
        assert!(dmg.wear_level > 0.0, "Overrev should cause wear");
    }

    #[test]
    fn test_bearing_damage_from_oil_starvation() {
        let (mut thermal, cooling, mut lub, mut dmg) = make_test_systems();
        lub.oil_level = 0.0;
        for _ in 0..500 {
            update_engine(
                &mut thermal,
                &cooling,
                &mut lub,
                &mut dmg,
                3000.0,
                7000.0,
                0.5,
                0.0,
                0.0,
                0.1,
            );
        }
        assert!(
            dmg.bearing_damage > 0.0,
            "Oil starvation should damage bearings"
        );
    }

    #[test]
    fn test_seizure() {
        let (_, mut lub, mut dmg) = (
            EngineThermal::default(),
            LubricationSystem::default(),
            EngineDamage::default(),
        );
        lub.oil_level = 0.0;
        lub.oil_pressure = 0.0; // Simulate complete oil pressure loss
        for _ in 0..500 {
            dmg.check_oil_starvation(lub.oil_pressure);
        }
        assert!(dmg.is_seized, "Extreme starvation should seize engine");
    }

    #[test]
    fn test_fire_risk() {
        let (mut thermal, mut cooling, mut lub, mut dmg) = make_test_systems();
        cooling.damage_factor = 0.0; // Disable cooling
        thermal.coolant_temp = 145.0;
        dmg.wear_level = 0.9;
        for _ in 0..200 {
            update_engine(
                &mut thermal,
                &cooling,
                &mut lub,
                &mut dmg,
                6000.0,
                7000.0,
                1.0,
                0.0,
                0.0,
                1.0,
            );
        }
        assert!(
            dmg.fire_timer > 0.0 || dmg.is_on_fire,
            "Extreme conditions should risk fire"
        );
    }

    #[test]
    fn test_persistent_damage() {
        let mut dmg = EngineDamage::default();
        dmg.bearing_damage = 0.5;
        dmg.wear_level = 0.3;
        // Simulate time passing with no further issues
        dmg.update(10.0);
        assert!(
            dmg.bearing_damage >= 0.5,
            "Bearing damage should not self-repair"
        );
        assert!(dmg.wear_level >= 0.3, "Wear should not self-repair");
    }

    #[test]
    fn test_limp_home() {
        let (mut thermal, cooling, mut lub, mut dmg) = make_test_systems();
        dmg.bearing_damage = 0.6;
        let telem = update_engine(
            &mut thermal,
            &cooling,
            &mut lub,
            &mut dmg,
            3000.0,
            7000.0,
            0.5,
            0.0,
            0.0,
            0.1,
        );
        assert!(
            telem.derate_factor < 0.8,
            "Severe damage should significantly derate"
        );
        assert!(telem.has_warning, "Should trigger warning");
    }

    #[test]
    fn test_cooling_damaged_reduces_effectiveness() {
        let mut cooling = CoolingSystem::default();
        let rate_healthy = cooling.cooling_rate(95.0, 20.0);
        cooling.damage_factor = 0.3;
        let rate_damaged = cooling.cooling_rate(95.0, 20.0);
        assert!(
            rate_damaged < rate_healthy,
            "Damaged cooling should be less effective"
        );
    }
}
