/**
 * Versioned telemetry model for virtual OBD-II PIDs / CAN signals.
 *
 * Schema version is bumped when signals are added, removed, or renamed.
 * Consumers should check compatibilityVersion before registering signals.
 */

export type SubsystemId =
  | 'engine'
  | 'drivetrain'
  | 'suspension'
  | 'tires'
  | 'body'
  | 'fuel'
  | 'electrical'
  | 'vehicle'
  | 'safety'

export type SignalCategory = 'gauge' | 'indicator' | 'warning' | 'chart'

export interface TelemetrySignalDefinition {
  id: string
  label: string
  unit: string
  subsystem: SubsystemId
  category: SignalCategory
  minValue?: number
  maxValue?: number
  warningThreshold?: number
  faultThreshold?: number
  description: string
}

/** Bump when VIRTUAL_OBD_PIDS changes shape. */
export const TELEMETRY_SCHEMA_VERSION = 2

// ---------------------------------------------------------------------------
// Virtual OBD-II PIDs / CAN signals
// ---------------------------------------------------------------------------

export const VIRTUAL_OBD_PIDS: readonly TelemetrySignalDefinition[] = [
  // ── Engine ───────────────────────────────────────────────────────────
  {
    id: 'engine.rpm',
    label: 'Engine RPM',
    unit: 'rpm',
    subsystem: 'engine',
    category: 'gauge',
    minValue: 0,
    maxValue: 9000,
    warningThreshold: 7000,
    faultThreshold: 8500,
    description: 'Crankshaft revolutions per minute',
  },
  {
    id: 'engine.coolant_temp',
    label: 'Coolant Temp',
    unit: '°C',
    subsystem: 'engine',
    category: 'gauge',
    minValue: -40,
    maxValue: 215,
    warningThreshold: 105,
    faultThreshold: 120,
    description: 'Engine coolant temperature',
  },
  {
    id: 'engine.coolant_pressure',
    label: 'Coolant Pressure',
    unit: 'kPa',
    subsystem: 'engine',
    category: 'gauge',
    minValue: 0,
    maxValue: 300,
    warningThreshold: 200,
    faultThreshold: 250,
    description: 'Cooling system pressure',
  },
  {
    id: 'engine.oil_temp',
    label: 'Oil Temp',
    unit: '°C',
    subsystem: 'engine',
    category: 'gauge',
    minValue: -40,
    maxValue: 160,
    warningThreshold: 125,
    faultThreshold: 150,
    description: 'Engine oil temperature',
  },
  {
    id: 'engine.oil_pressure',
    label: 'Oil Pressure',
    unit: 'kPa',
    subsystem: 'engine',
    category: 'gauge',
    minValue: 0,
    maxValue: 800,
    warningThreshold: 600,
    faultThreshold: 700,
    description: 'Engine oil pressure',
  },
  {
    id: 'engine.intake_temp',
    label: 'Intake Air Temp',
    unit: '°C',
    subsystem: 'engine',
    category: 'gauge',
    minValue: -40,
    maxValue: 80,
    warningThreshold: 50,
    faultThreshold: 70,
    description: 'Intake manifold air temperature',
  },
  {
    id: 'engine.exhaust_temp',
    label: 'Exhaust Gas Temp',
    unit: '°C',
    subsystem: 'engine',
    category: 'gauge',
    minValue: 0,
    maxValue: 1100,
    warningThreshold: 850,
    faultThreshold: 1000,
    description: 'Exhaust gas temperature',
  },
  {
    id: 'engine.load',
    label: 'Engine Load',
    unit: '%',
    subsystem: 'engine',
    category: 'gauge',
    minValue: 0,
    maxValue: 100,
    warningThreshold: 85,
    faultThreshold: 95,
    description: 'Current engine load percentage',
  },
  {
    id: 'engine.afr',
    label: 'Air-Fuel Ratio',
    unit: '',
    subsystem: 'engine',
    category: 'chart',
    minValue: 10,
    maxValue: 20,
    warningThreshold: 15.5,
    faultThreshold: 16.5,
    description: 'Lambda air-fuel ratio (14.7 stoichiometric)',
  },
  {
    id: 'engine.knock_count',
    label: 'Knock Count',
    unit: '',
    subsystem: 'engine',
    category: 'indicator',
    minValue: 0,
    maxValue: 999,
    warningThreshold: 3,
    faultThreshold: 10,
    description: 'Detonation event count per cycle',
  },
  {
    id: 'engine.thermal_headroom',
    label: 'Thermal Headroom',
    unit: '°C',
    subsystem: 'engine',
    category: 'chart',
    minValue: 0,
    maxValue: 100,
    warningThreshold: 10,
    faultThreshold: 0,
    description: 'Margin between coolant temp and fault threshold',
  },

  // ── Drivetrain ──────────────────────────────────────────────────────
  {
    id: 'drivetrain.gear',
    label: 'Current Gear',
    unit: '',
    subsystem: 'drivetrain',
    category: 'indicator',
    minValue: 0,
    maxValue: 6,
    description: 'Current transmission gear (0 = neutral)',
  },
  {
    id: 'drivetrain.clutch_engagement',
    label: 'Clutch Engagement',
    unit: '%',
    subsystem: 'drivetrain',
    category: 'gauge',
    minValue: 0,
    maxValue: 100,
    description: 'Clutch plate engagement percentage',
  },
  {
    id: 'drivetrain.transmission_temp',
    label: 'Transmission Temp',
    unit: '°C',
    subsystem: 'drivetrain',
    category: 'gauge',
    minValue: -20,
    maxValue: 150,
    warningThreshold: 110,
    faultThreshold: 130,
    description: 'Transmission fluid temperature',
  },
  {
    id: 'drivetrain.torque_output',
    label: 'Torque Output',
    unit: 'N·m',
    subsystem: 'drivetrain',
    category: 'chart',
    minValue: 0,
    maxValue: 800,
    description: 'Output torque at driveshaft',
  },

  // ── Vehicle (chassis dynamics) ──────────────────────────────────────
  {
    id: 'vehicle.speed',
    label: 'Vehicle Speed',
    unit: 'km/h',
    subsystem: 'vehicle',
    category: 'gauge',
    minValue: 0,
    maxValue: 320,
    description: 'Ground speed',
  },
  {
    id: 'vehicle.acceleration',
    label: 'Acceleration',
    unit: 'm/s²',
    subsystem: 'vehicle',
    category: 'chart',
    minValue: -30,
    maxValue: 30,
    description: 'Longitudinal acceleration',
  },
  {
    id: 'vehicle.wheel_speed_fl',
    label: 'Wheel Speed FL',
    unit: 'km/h',
    subsystem: 'vehicle',
    category: 'chart',
    minValue: 0,
    maxValue: 350,
    description: 'Front-left wheel speed',
  },
  {
    id: 'vehicle.wheel_speed_fr',
    label: 'Wheel Speed FR',
    unit: 'km/h',
    subsystem: 'vehicle',
    category: 'chart',
    minValue: 0,
    maxValue: 350,
    description: 'Front-right wheel speed',
  },
  {
    id: 'vehicle.wheel_speed_rl',
    label: 'Wheel Speed RL',
    unit: 'km/h',
    subsystem: 'vehicle',
    category: 'chart',
    minValue: 0,
    maxValue: 350,
    description: 'Rear-left wheel speed',
  },
  {
    id: 'vehicle.wheel_speed_rr',
    label: 'Wheel Speed RR',
    unit: 'km/h',
    subsystem: 'vehicle',
    category: 'chart',
    minValue: 0,
    maxValue: 350,
    description: 'Rear-right wheel speed',
  },
  {
    id: 'vehicle.slip_ratio',
    label: 'Slip Ratio',
    unit: '',
    subsystem: 'vehicle',
    category: 'chart',
    minValue: -1,
    maxValue: 1,
    description: 'Longitudinal tire slip ratio',
  },
  {
    id: 'vehicle.slip_angle',
    label: 'Slip Angle',
    unit: '°',
    subsystem: 'vehicle',
    category: 'chart',
    minValue: -30,
    maxValue: 30,
    description: 'Lateral tire slip angle',
  },

  // ── Suspension ──────────────────────────────────────────────────────
  {
    id: 'suspension.compression_fl',
    label: 'Susp. Comp FL',
    unit: '%',
    subsystem: 'suspension',
    category: 'indicator',
    minValue: 0,
    maxValue: 100,
    description: 'Front-left suspension compression',
  },
  {
    id: 'suspension.compression_fr',
    label: 'Susp. Comp FR',
    unit: '%',
    subsystem: 'suspension',
    category: 'indicator',
    minValue: 0,
    maxValue: 100,
    description: 'Front-right suspension compression',
  },
  {
    id: 'suspension.compression_rl',
    label: 'Susp. Comp RL',
    unit: '%',
    subsystem: 'suspension',
    category: 'indicator',
    minValue: 0,
    maxValue: 100,
    description: 'Rear-left suspension compression',
  },
  {
    id: 'suspension.compression_rr',
    label: 'Susp. Comp RR',
    unit: '%',
    subsystem: 'suspension',
    category: 'indicator',
    minValue: 0,
    maxValue: 100,
    description: 'Rear-right suspension compression',
  },
  {
    id: 'suspension.load_fl',
    label: 'Susp. Load FL',
    unit: 'kg',
    subsystem: 'suspension',
    category: 'chart',
    minValue: 0,
    maxValue: 1000,
    description: 'Front-left suspension load',
  },
  {
    id: 'suspension.load_fr',
    label: 'Susp. Load FR',
    unit: 'kg',
    subsystem: 'suspension',
    category: 'chart',
    minValue: 0,
    maxValue: 1000,
    description: 'Front-right suspension load',
  },
  {
    id: 'suspension.load_rl',
    label: 'Susp. Load RL',
    unit: 'kg',
    subsystem: 'suspension',
    category: 'chart',
    minValue: 0,
    maxValue: 1000,
    description: 'Rear-left suspension load',
  },
  {
    id: 'suspension.load_rr',
    label: 'Susp. Load RR',
    unit: 'kg',
    subsystem: 'suspension',
    category: 'chart',
    minValue: 0,
    maxValue: 1000,
    description: 'Rear-right suspension load',
  },
  {
    id: 'suspension.travel_fl',
    label: 'Susp. Travel FL',
    unit: 'mm',
    subsystem: 'suspension',
    category: 'chart',
    minValue: 0,
    maxValue: 120,
    description: 'Front-left suspension travel',
  },
  {
    id: 'suspension.travel_fr',
    label: 'Susp. Travel FR',
    unit: 'mm',
    subsystem: 'suspension',
    category: 'chart',
    minValue: 0,
    maxValue: 120,
    description: 'Front-right suspension travel',
  },
  {
    id: 'suspension.travel_rl',
    label: 'Susp. Travel RL',
    unit: 'mm',
    subsystem: 'suspension',
    category: 'chart',
    minValue: 0,
    maxValue: 120,
    description: 'Rear-left suspension travel',
  },
  {
    id: 'suspension.travel_rr',
    label: 'Susp. Travel RR',
    unit: 'mm',
    subsystem: 'suspension',
    category: 'chart',
    minValue: 0,
    maxValue: 120,
    description: 'Rear-right suspension travel',
  },

  // ── Tires ───────────────────────────────────────────────────────────
  {
    id: 'tire.temp_fl',
    label: 'Tire Temp FL',
    unit: '°C',
    subsystem: 'tires',
    category: 'gauge',
    minValue: 0,
    maxValue: 150,
    warningThreshold: 100,
    faultThreshold: 130,
    description: 'Front-left tire surface temperature',
  },
  {
    id: 'tire.temp_fr',
    label: 'Tire Temp FR',
    unit: '°C',
    subsystem: 'tires',
    category: 'gauge',
    minValue: 0,
    maxValue: 150,
    warningThreshold: 100,
    faultThreshold: 130,
    description: 'Front-right tire surface temperature',
  },
  {
    id: 'tire.temp_rl',
    label: 'Tire Temp RL',
    unit: '°C',
    subsystem: 'tires',
    category: 'gauge',
    minValue: 0,
    maxValue: 150,
    warningThreshold: 100,
    faultThreshold: 130,
    description: 'Rear-left tire surface temperature',
  },
  {
    id: 'tire.temp_rr',
    label: 'Tire Temp RR',
    unit: '°C',
    subsystem: 'tires',
    category: 'gauge',
    minValue: 0,
    maxValue: 150,
    warningThreshold: 100,
    faultThreshold: 130,
    description: 'Rear-right tire surface temperature',
  },
  {
    id: 'tire.pressure_fl',
    label: 'Tire Pressure FL',
    unit: 'bar',
    subsystem: 'tires',
    category: 'gauge',
    minValue: 0,
    maxValue: 5,
    warningThreshold: 2.8,
    faultThreshold: 3.5,
    description: 'Front-left tire pressure',
  },
  {
    id: 'tire.pressure_fr',
    label: 'Tire Pressure FR',
    unit: 'bar',
    subsystem: 'tires',
    category: 'gauge',
    minValue: 0,
    maxValue: 5,
    warningThreshold: 2.8,
    faultThreshold: 3.5,
    description: 'Front-right tire pressure',
  },
  {
    id: 'tire.pressure_rl',
    label: 'Tire Pressure RL',
    unit: 'bar',
    subsystem: 'tires',
    category: 'gauge',
    minValue: 0,
    maxValue: 5,
    warningThreshold: 2.8,
    faultThreshold: 3.5,
    description: 'Rear-left tire pressure',
  },
  {
    id: 'tire.pressure_rr',
    label: 'Tire Pressure RR',
    unit: 'bar',
    subsystem: 'tires',
    category: 'gauge',
    minValue: 0,
    maxValue: 5,
    warningThreshold: 2.8,
    faultThreshold: 3.5,
    description: 'Rear-right tire pressure',
  },
  {
    id: 'tire.wear_fl',
    label: 'Tire Wear FL',
    unit: '%',
    subsystem: 'tires',
    category: 'indicator',
    minValue: 0,
    maxValue: 100,
    warningThreshold: 20,
    faultThreshold: 5,
    description: 'Front-left tire remaining tread life',
  },
  {
    id: 'tire.wear_fr',
    label: 'Tire Wear FR',
    unit: '%',
    subsystem: 'tires',
    category: 'indicator',
    minValue: 0,
    maxValue: 100,
    warningThreshold: 20,
    faultThreshold: 5,
    description: 'Front-right tire remaining tread life',
  },
  {
    id: 'tire.wear_rl',
    label: 'Tire Wear RL',
    unit: '%',
    subsystem: 'tires',
    category: 'indicator',
    minValue: 0,
    maxValue: 100,
    warningThreshold: 20,
    faultThreshold: 5,
    description: 'Rear-left tire remaining tread life',
  },
  {
    id: 'tire.wear_rr',
    label: 'Tire Wear RR',
    unit: '%',
    subsystem: 'tires',
    category: 'indicator',
    minValue: 0,
    maxValue: 100,
    warningThreshold: 20,
    faultThreshold: 5,
    description: 'Rear-right tire remaining tread life',
  },
  {
    id: 'tire.grip_fl',
    label: 'Tire Grip FL',
    unit: '',
    subsystem: 'tires',
    category: 'chart',
    minValue: 0,
    maxValue: 1,
    description: 'Front-left tire grip coefficient',
  },
  {
    id: 'tire.grip_fr',
    label: 'Tire Grip FR',
    unit: '',
    subsystem: 'tires',
    category: 'chart',
    minValue: 0,
    maxValue: 1,
    description: 'Front-right tire grip coefficient',
  },
  {
    id: 'tire.grip_rl',
    label: 'Tire Grip RL',
    unit: '',
    subsystem: 'tires',
    category: 'chart',
    minValue: 0,
    maxValue: 1,
    description: 'Rear-left tire grip coefficient',
  },
  {
    id: 'tire.grip_rr',
    label: 'Tire Grip RR',
    unit: '',
    subsystem: 'tires',
    category: 'chart',
    minValue: 0,
    maxValue: 1,
    description: 'Rear-right tire grip coefficient',
  },
  {
    id: 'tire.damage_fl',
    label: 'Tire Damage FL',
    unit: '%',
    subsystem: 'tires',
    category: 'warning',
    minValue: 0,
    maxValue: 100,
    warningThreshold: 10,
    faultThreshold: 50,
    description: 'Front-left tire damage level',
  },
  {
    id: 'tire.damage_fr',
    label: 'Tire Damage FR',
    unit: '%',
    subsystem: 'tires',
    category: 'warning',
    minValue: 0,
    maxValue: 100,
    warningThreshold: 10,
    faultThreshold: 50,
    description: 'Front-right tire damage level',
  },
  {
    id: 'tire.damage_rl',
    label: 'Tire Damage RL',
    unit: '%',
    subsystem: 'tires',
    category: 'warning',
    minValue: 0,
    maxValue: 100,
    warningThreshold: 10,
    faultThreshold: 50,
    description: 'Rear-left tire damage level',
  },
  {
    id: 'tire.damage_rr',
    label: 'Tire Damage RR',
    unit: '%',
    subsystem: 'tires',
    category: 'warning',
    minValue: 0,
    maxValue: 100,
    warningThreshold: 10,
    faultThreshold: 50,
    description: 'Rear-right tire damage level',
  },

  // ── Body (deformation) ──────────────────────────────────────────────
  {
    id: 'body.deformation_depth',
    label: 'Deformation Depth',
    unit: 'mm',
    subsystem: 'body',
    category: 'warning',
    minValue: 0,
    maxValue: 500,
    warningThreshold: 50,
    faultThreshold: 200,
    description: 'Maximum beam deformation depth',
  },
  {
    id: 'body.broken_beams',
    label: 'Broken Beams',
    unit: '',
    subsystem: 'body',
    category: 'warning',
    minValue: 0,
    maxValue: 999,
    warningThreshold: 1,
    faultThreshold: 5,
    description: 'Number of broken structural beams',
  },
  {
    id: 'body.impact_severity',
    label: 'Impact Severity',
    unit: 'G',
    subsystem: 'body',
    category: 'warning',
    minValue: 0,
    maxValue: 100,
    warningThreshold: 15,
    faultThreshold: 40,
    description: 'Peak impact deceleration in G-force',
  },
  {
    id: 'body.alignment_offset',
    label: 'Alignment Offset',
    unit: 'mm',
    subsystem: 'body',
    category: 'indicator',
    minValue: -50,
    maxValue: 50,
    warningThreshold: 10,
    faultThreshold: 25,
    description: 'Frame alignment offset from baseline',
  },

  // ── Fuel ─────────────────────────────────────────────────────────────
  {
    id: 'fuel.level',
    label: 'Fuel Level',
    unit: 'L',
    subsystem: 'fuel',
    category: 'gauge',
    minValue: 0,
    maxValue: 80,
    warningThreshold: 10,
    faultThreshold: 3,
    description: 'Fuel tank level',
  },
  {
    id: 'fuel.flow_rate',
    label: 'Fuel Flow Rate',
    unit: 'L/h',
    subsystem: 'fuel',
    category: 'chart',
    minValue: 0,
    maxValue: 120,
    description: 'Current fuel consumption rate',
  },
  {
    id: 'fuel.range',
    label: 'Estimated Range',
    unit: 'km',
    subsystem: 'fuel',
    category: 'gauge',
    minValue: 0,
    maxValue: 800,
    warningThreshold: 50,
    faultThreshold: 10,
    description: 'Estimated driving range on remaining fuel',
  },

  // ── Electrical ──────────────────────────────────────────────────────
  {
    id: 'electrical.battery_voltage',
    label: 'Battery Voltage',
    unit: 'V',
    subsystem: 'electrical',
    category: 'gauge',
    minValue: 0,
    maxValue: 18,
    warningThreshold: 11.5,
    faultThreshold: 10.5,
    description: 'Battery terminal voltage',
  },
  {
    id: 'electrical.fuel_pump',
    label: 'Fuel Pump',
    unit: 'A',
    subsystem: 'electrical',
    category: 'indicator',
    minValue: 0,
    maxValue: 10,
    warningThreshold: 8,
    faultThreshold: 9,
    description: 'Fuel pump current draw',
  },
  {
    id: 'electrical.warning_lamp',
    label: 'Warning Lamp',
    unit: '',
    subsystem: 'electrical',
    category: 'warning',
    minValue: 0,
    maxValue: 1,
    description: 'Dashboard warning lamp state (0 = off, 1 = on)',
  },

  // ── Engine Stress Accumulators ──────────────────────────────────────
  {
    id: 'engine.stress_thermal',
    label: 'Thermal Stress',
    unit: '',
    subsystem: 'engine',
    category: 'indicator',
    minValue: 0,
    maxValue: 1,
    warningThreshold: 0.5,
    faultThreshold: 0.8,
    description: 'Cumulative thermal stress (0-1)',
  },
  {
    id: 'engine.stress_oil',
    label: 'Oil Starvation Stress',
    unit: '',
    subsystem: 'engine',
    category: 'indicator',
    minValue: 0,
    maxValue: 1,
    warningThreshold: 0.5,
    faultThreshold: 0.8,
    description: 'Cumulative oil starvation stress (0-1)',
  },
  {
    id: 'engine.stress_overrev',
    label: 'Over-Rev Stress',
    unit: '',
    subsystem: 'engine',
    category: 'indicator',
    minValue: 0,
    maxValue: 1,
    warningThreshold: 0.5,
    faultThreshold: 0.8,
    description: 'Cumulative over-rev stress (0-1)',
  },
  {
    id: 'engine.stress_lugging',
    label: 'Lugging Stress',
    unit: '',
    subsystem: 'engine',
    category: 'indicator',
    minValue: 0,
    maxValue: 1,
    warningThreshold: 0.5,
    faultThreshold: 0.8,
    description: 'Cumulative lugging stress (0-1)',
  },
  {
    id: 'engine.derate_factor',
    label: 'Derate Factor',
    unit: '',
    subsystem: 'engine',
    category: 'gauge',
    minValue: 0,
    maxValue: 1,
    warningThreshold: 0.7,
    faultThreshold: 0.3,
    description: 'Power derate multiplier (0-1)',
  },
  {
    id: 'engine.blowup_state',
    label: 'Blow-Up State',
    unit: '',
    subsystem: 'engine',
    category: 'warning',
    minValue: 0,
    maxValue: 5,
    warningThreshold: 1,
    faultThreshold: 3,
    description: 'Blow-up stage (0=ok, 1=warn, 2=derate, 3=rough, 4=failure, 5=fire)',
  },

  // ── Safety: ABS ─────────────────────────────────────────────────────
  {
    id: 'safety.abs_wheel_speed_fl',
    label: 'ABS Wheel Speed FL',
    unit: 'km/h',
    subsystem: 'safety',
    category: 'chart',
    minValue: 0,
    maxValue: 350,
    description: 'Front-left wheel speed (km/h)',
  },
  {
    id: 'safety.abs_wheel_speed_fr',
    label: 'ABS Wheel Speed FR',
    unit: 'km/h',
    subsystem: 'safety',
    category: 'chart',
    minValue: 0,
    maxValue: 350,
    description: 'Front-right wheel speed (km/h)',
  },
  {
    id: 'safety.abs_wheel_speed_rl',
    label: 'ABS Wheel Speed RL',
    unit: 'km/h',
    subsystem: 'safety',
    category: 'chart',
    minValue: 0,
    maxValue: 350,
    description: 'Rear-left wheel speed (km/h)',
  },
  {
    id: 'safety.abs_wheel_speed_rr',
    label: 'ABS Wheel Speed RR',
    unit: 'km/h',
    subsystem: 'safety',
    category: 'chart',
    minValue: 0,
    maxValue: 350,
    description: 'Rear-right wheel speed (km/h)',
  },
  {
    id: 'safety.abs_active',
    label: 'ABS Active',
    unit: '',
    subsystem: 'safety',
    category: 'indicator',
    minValue: 0,
    maxValue: 1,
    description: 'ABS currently modulating',
  },
  {
    id: 'safety.abs_brake_pressure_mod',
    label: 'ABS Brake Pressure Modifier',
    unit: '',
    subsystem: 'safety',
    category: 'gauge',
    minValue: 0,
    maxValue: 1,
    description: 'ABS brake pressure modifier (0-1)',
  },
  {
    id: 'safety.abs_mode',
    label: 'ABS Mode',
    unit: '',
    subsystem: 'safety',
    category: 'indicator',
    description: 'ABS mode (enabled/sport/disabled)',
  },

  // ── Safety: Traction Control ────────────────────────────────────────
  {
    id: 'safety.tc_active',
    label: 'TC Active',
    unit: '',
    subsystem: 'safety',
    category: 'indicator',
    minValue: 0,
    maxValue: 1,
    description: 'TC currently intervening',
  },
  {
    id: 'safety.tc_throttle_mod',
    label: 'TC Throttle Modifier',
    unit: '',
    subsystem: 'safety',
    category: 'gauge',
    minValue: 0,
    maxValue: 1,
    description: 'TC throttle modifier (0-1)',
  },
  {
    id: 'safety.tc_mode',
    label: 'TC Mode',
    unit: '',
    subsystem: 'safety',
    category: 'indicator',
    description: 'TC mode',
  },

  // ── Safety: VSC ─────────────────────────────────────────────────────
  {
    id: 'safety.vsc_yaw_error',
    label: 'VSC Yaw Error',
    unit: 'deg/s',
    subsystem: 'safety',
    category: 'chart',
    minValue: -90,
    maxValue: 90,
    warningThreshold: 5,
    description: 'Yaw rate error (deg/s)',
  },
  {
    id: 'safety.vsc_correction_active',
    label: 'VSC Correction Active',
    unit: '',
    subsystem: 'safety',
    category: 'indicator',
    minValue: 0,
    maxValue: 1,
    description: 'VSC currently correcting',
  },
  {
    id: 'safety.vsc_brake_torque_l',
    label: 'VSC Brake Torque L',
    unit: 'Nm',
    subsystem: 'safety',
    category: 'chart',
    minValue: 0,
    maxValue: 5000,
    description: 'VSC left brake torque (Nm)',
  },
  {
    id: 'safety.vsc_brake_torque_r',
    label: 'VSC Brake Torque R',
    unit: 'Nm',
    subsystem: 'safety',
    category: 'chart',
    minValue: 0,
    maxValue: 5000,
    description: 'VSC right brake torque (Nm)',
  },
  {
    id: 'safety.vsc_torque_reduction',
    label: 'VSC Torque Reduction',
    unit: '',
    subsystem: 'safety',
    category: 'gauge',
    minValue: 0,
    maxValue: 1,
    description: 'VSC engine torque reduction (0-1)',
  },
  {
    id: 'safety.vsc_mode',
    label: 'VSC Mode',
    unit: '',
    subsystem: 'safety',
    category: 'indicator',
    description: 'VSC mode',
  },

  // ── Safety: ADAS ────────────────────────────────────────────────────
  {
    id: 'safety.adas_time_to_collision',
    label: 'Time to Collision',
    unit: 's',
    subsystem: 'safety',
    category: 'indicator',
    minValue: 0,
    maxValue: 30,
    warningThreshold: 2,
    faultThreshold: 0.8,
    description: 'Time to collision (s)',
  },
  {
    id: 'safety.adas_target_detected',
    label: 'ADAS Target Detected',
    unit: '',
    subsystem: 'safety',
    category: 'indicator',
    minValue: 0,
    maxValue: 1,
    description: 'ADAS target detected',
  },
  {
    id: 'safety.adas_target_distance',
    label: 'ADAS Target Distance',
    unit: 'm',
    subsystem: 'safety',
    category: 'gauge',
    minValue: 0,
    maxValue: 300,
    warningThreshold: 30,
    faultThreshold: 10,
    description: 'Target distance (m)',
  },
  {
    id: 'safety.adas_aeb_active',
    label: 'AEB Active',
    unit: '',
    subsystem: 'safety',
    category: 'indicator',
    minValue: 0,
    maxValue: 1,
    description: 'Automatic emergency braking active',
  },
  {
    id: 'safety.adas_acc_target_speed',
    label: 'ACC Target Speed',
    unit: 'km/h',
    subsystem: 'safety',
    category: 'gauge',
    minValue: 0,
    maxValue: 250,
    description: 'ACC target speed (km/h)',
  },
  {
    id: 'safety.adas_ldw_warning',
    label: 'LDW Warning',
    unit: '',
    subsystem: 'safety',
    category: 'warning',
    minValue: 0,
    maxValue: 1,
    description: 'Lane departure warning active',
  },
  {
    id: 'safety.adas_sensor_faults',
    label: 'ADAS Sensor Faults',
    unit: '',
    subsystem: 'safety',
    category: 'warning',
    minValue: 0,
    maxValue: 255,
    warningThreshold: 1,
    faultThreshold: 4,
    description: 'Active sensor faults (bitmask)',
  },
] as const
